version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: deploy
          command: git ftp push --user "${username}" --passwd "${password}" ${ftp_location}
workflows:
  master-deploy:
    jobs:
      - build
          filters:
            branches:
              only: master